# basic options, 1 can say whatever here
title: My Test Blog
author: Mora Moloi
email: thibelloalex@gmail.com
description: Catch up on the latest news and important updates about your country and countries worldwide.
facebook_username: Alex Thibello Motebang
instagram_username: thibello_motebang
github_username: ThibelloMotebang

# Build settings
theme: minima
